django_project/urls.py
from django.contrib import admin
from django.urls import path
from appzinho import views

urlpatterns = [
  path('', views.homepage, name="home"),
  path('users', views.create_user),
  path('users/login/', views.login_user, name="login"),
  path('users/logout/', views.logout_user, name="logout"),
  path('top-movies', views.top_movies),
  path('top-movies/update/<id>', views.update_top_movies),
  path('top-movies/delete/<id>', views.delete_top_movies),
  path('movies', views.movies),
  path('movies/update/<id>', views.update_movies),
  path('movies/delete/<id>', views.delete_movies),
  path('admin/', admin.site.urls),
]

appzinho/models.py
from django.db import models

# Create your models here.
class FilmesFamosos(models.Model):
  title = models.CharField(max_length=50)
  main_character = models.CharField(max_length=50)
  genre = models.CharField(max_length=20)
  release_date = models.DateField()


class TopFilmes(models.Model):
  OPTIONS = [
    ("S", "Sad"),
    ("H", "Happy"),
    ("M", "Mixed"),
  ]
  title = models.CharField(max_length=50)
  main_character = models.CharField(max_length=50)
  feelings = models.CharField(max_length=1, choices=OPTIONS)
  position_in_top = models.IntegerField()
  release_date = models.DateField()

class Nomeados(models.Model):
  title = models.CharField(max_length=50)
  nominated = models.CharField(max_length=10)
  year = models.PositiveIntegerField()

appzinho/forms.py
from django.forms import ModelForm
from .models import FilmesFamosos

class FilmesForm(ModelForm):
  class Meta:
    model = FilmesFamosos
    fields =["title","main_character","genre","release_date"]

appzinho/views.py
from django.shortcuts import render, redirect
from .models import FilmesFamosos, TopFilmes, Nomeados
from .forms import FilmesForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

@login_required
def homepage(request):
  filmes = FilmesFamosos.objects.all()
  top = TopFilmes.objects.all()
  nomeados = Nomeados.objects.all()
  return render(request, "home.html", context={
    "filmes":filmes,
    "top_filmes":top,
    "nomeados_filmes": nomeados
  })

@login_required
def top_movies(request):
  options = TopFilmes.feelings.field.choices
  if request.method=="POST":
    TopFilmes.objects.create(
      title = request.POST["title"],
      main_character = request.POST["main_character"],
      feelings = request.POST["feelings"],
      position_in_top = request.POST["position_in_top"],
      release_date = request.POST["release_date"]
    )
    return redirect("home")  
    
  return render(request,"forms.html", context={"action":"Adicionar","options":options})

@login_required
def update_top_movies(request,id):
  top = TopFilmes.objects.get(id=id)
  options = TopFilmes.feelings.field.choices
  if request.method=="POST":
    top.title = request.POST["title"]
    top.main_character = request.POST["main_character"]
    top.feelings = request.POST["feelings"]
    top.position_in_top = request.POST["position_in_top"]
    top.release_date = request.POST["release_date"]
    top.save()
    return redirect("home")  
  return render(request,"forms.html", context={"action":"Atualizar","top_filmes":top,"options":options})

@login_required
def delete_top_movies(request,id):
  top = TopFilmes.objects.get(id=id)
  if request.method=="POST":
    if "confirm" in request.POST:
      top.delete()
    return redirect("home")  
  return render(request,"are_you_sure.html", context={"top_filmes":top})

@login_required
def movies(request):
  form = FilmesForm()
  if request.method =='POST':
    form = FilmesForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect("home") 
  return render(request, "forms1.html", context={"action":"Adicionar","form":form})

@login_required
def update_movies(request,id):
  filmes = FilmesFamosos.objects.get(id=id)
  form = FilmesForm(instance = filmes)
  if request.method=="POST":
    form = FilmesForm(request.POST, instance=filmes)
    if form.is_valid():
      form.save()
      return redirect("home") 
  return render(request,"forms1.html", context={"action":"Atualizar","form":form})

@login_required
def delete_movies(request,id):
  filmes = FilmesFamosos.objects.get(id=id)
  if request.method=="POST":
    if "confirm" in request.POST:
      filmes.delete()
    return redirect("home")  
  return render(request,"are_you_sure.html", context={"filmes":filmes})

def create_user(request):
  if request.method == "POST":
    user = User.objects.create_user(
      request.POST["username"],
      request.POST["email"],
      request.POST["password"]      
    )
    user.save()
    return redirect("home")
  return render(request,"register.html", context={"action":"Adicionar"})

def login_user(request):
  if request.method =="POST":
    user = authenticate(
      username = request.POST["username"],
      password = request.POST["password"] 
    )
    if user != None:
      login(request, user)
    else:
      return render(request,"login.html",context={"error_msg":"Usuário não encontrado! =c"})
    if request.user.is_authenticated:
      return redirect("home")
    return render(request,"login.html",context={"error_msg":"Usuário não conseguiu ser logado! =c"})
  return render(request,"login.html")

def logout_user(request):
  logout(request)
  return redirect("login")

appzinho/templates/are_you_sure.html
<h1>Tem certeza que deseja deletar o filme "{{top_filmes.title}}" do top?</h1>
<br>
<form method="post">
  {% csrf_token %}
  <input type="submit"  name="confirm" value="Sim">
  <input type="submit"  value="Não">
</form>

appzinho/templates/forms.html
<h3>{{action}} outro filme no top 4</h3>
<br>
<br>
<form method="post">
  {% csrf_token %}
  <div>
    <label>Título:</label>
    <input name="title" value="{{top_filmes.title}}">
  </div>
  <div>
    <label>Personagem principal:</label>
    <input name="main_character" value="{{top_filmes.main_character}}">
  </div>
  <div>
    <label>Sentimentos:</label>
    <select name="feelings" required="" id="id_feelings" value="{{top_filmes.feelings}}">
      {% for opt in options %}
      <option value="{{ opt.0 }}">{{ opt.1 }}</option>
      {% endfor %}
    </select>
  </div>
  <div>
    <label>Posição no top:</label>
    <input name="position_in_top" value="{{top_filmes.position_in_top}}">
  </div>
  <div>
    <label>Data de lançamento:</label>
    <input type="date" name="release_date" value="{{top_filmes.release_date}}">
  </div>
  <input type="submit" value="Registrar">
</form>

appzinho/templates/forms1.html
<h3>{{action}} outro filme no top 4</h3>
<br>
<br>
<form method="post">
  {% csrf_token %}
  {{form}}
  <input type ="submit">
</form>

appzinho/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>✨</title>
  <link href="{% static 'style.css'%}" rel="stylesheet" type="text/css" />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Signika+Negative:wght@300&family=Source+Serif+4:opsz@8..60&display=swap" rel="stylesheet">
  {% load static %}
</head>

<body>
  <div class="header">
    <h4>Maria Luiza Dutra Gonzalez de Almeida</h4>
    <h1>Studio Ghibli</h1>
    <br>
  </div>  
  <br>
  {% if request.user.is_authenticated %} 
    <b>Boas-vindas, </b>{{request.user.username}}!
    <a href="/users/logout/"> Sair da conta?</a>
    <br>
  {%endif%}
  <br>
  <div class="center-image">
    <img src="https://i.pinimg.com/originals/6d/9c/49/6d9c49c24dfc3f01420c0bbca656078e.gif">
    <img src="https://i0.wp.com/studioghibli.com.br/wp-content/uploads/2020/06/Studio_Ghibli_logo.png?w=640&ssl=1">
    <img src="https://i.pinimg.com/originals/6d/9c/49/6d9c49c24dfc3f01420c0bbca656078e.gif">
  </div>
  <br>  
  <p>
    O <a href="https://studioghibli.com.br/studioghibli/" target="_blank"><b>Studio Ghibli</b></a> é um estúdio japonês de cinema responsável por produzir muitas das <ins>melhores</ins> e <em>mais emocionantes</em> animações da <strong>indústria</strong>.
  </p> 

  <h3>Os seus filmes mais famosos são:</h3>
  <div class="list">
  <ul>
    {% for filme in filmes%}
    <li>{{ filme.title }}
    <a href="movies/update/{{filme.id}}"> Atualizar </a>
    <a href="movies/delete/{{filme.id}}"> <i>Remover</i> </a>
    </li>
    {% endfor %}
  </ul>
  <br>
  </div>
  <br>
  <a href="/movies">Adicionar novo filme na lista</a>
  <br>
  <h3>Top 4 filmes do Studio Ghibli (na <i>nossa</i> humilde opinião):</h3>
  <div class="list">
  <ol>
    {% for filme in top_filmes%}
    <li>{{ filme.title }} 
      <a href="top-movies/update/{{filme.id}}"> Atualizar </a>
      <a href="top-movies/delete/{{filme.id}}"> <i>Remover</i> </a>
    </li>
    {% endfor %}
  </ol>
  </div>
  <br>
  <a href="/top-movies">Adicionar novo filme no top 4</a>
  <br>
  <h3>Filmes que foram nomeados ou que ganharam um Oscar de melhor animação:</h3>
  <table class="center-table">
    <tr>
      <th>Nome de Filme</th>
      <th>Nomeação/Ganho</th>
      <th>Ano</th>
    </tr>
    {% for filme in nomeados_filmes%}
    <tr>
      <td>{{ filme.title }}</td>
      <td>{{ filme.nominated }}</td>
      <td>{{ filme.year }}</td>
    </tr>
    {% endfor %}
  </table>
  <br>
  <br>
    
</body>

</html>

appzinho/templates/login.html
<h1>Entre na sua conta:</h1>
<br>
<form method="post">
  {% csrf_token %}
  <div>
    <label>Nome de Usuário:</label>
    <input type="text" name="username">
  </div>
  <div>
    <label>Senha:</label>
    <input type="password" name="password" >
  </div>

  <input type="submit" value="Login">
  <br>
  <span style="color: red">{{ error_msg }}</span>
  <br>
  <a href="/users"> Criar conta? </a>
</form>

appzinho/templates/register.html
<h1>Adicionar usuário</h1>

<form method="post">
  {% csrf_token %}
  <div>
    <label>Nome de usuário:</label>
    <input type="text" name="username">
  </div>
  <div>
    <label>Email:</label>
    <input type="email" name="email">
  </div>
  <div>
    <label>Senha:</label>
    <input type="password" name="password">
  </div>
  <input type="submit" value="Registrar">
</form>